package com.example.hastanghubaga

import android.app.Application
import android.content.Context
import androidx.test.runner.AndroidJUnitRunner
import dagger.hilt.android.testing.HiltTestApplication

/**
 * Custom test runner used to enable Hilt dependency injection inside instrumented tests.
 *
 * ## Why This Exists
 * When running Android instrumented tests, the default `AndroidJUnitRunner`
 * initializes your real `Application` class.
 *
 * Hilt, however, requires a special test application (`HiltTestApplication`)
 * that is automatically generated by Hilt and knows how to:
 *
 * - Inject dependencies into test classes
 * - Provide test components instead of production components
 * - Respect `@HiltAndroidTest`
 * - Manage lifecycle-scoped test components
 *
 * This runner overrides `newApplication()` so that all instrumented tests use
 * **HiltTestApplication** instead of your production `Application`.
 *
 * ## When It Is Required
 * - Any time you use `@HiltAndroidTest`
 * - Any time a test needs access to injected dependencies
 * - When running tests that involve Activities, Fragments, Services, or BroadcastReceivers
 *
 * ## Setup Required
 * Add the runner to your `app/src/androidTest/AndroidManifest.xml`:
 *
 * ```
 * <instrumentation
 *     android:name="com.example.hastanghubaga.HiltTestRunner"
 *     android:targetPackage="com.example.hastanghubaga" />
 * ```
 *
 * Then update your Gradle config:
 *
 * ```
 * defaultConfig {
 *     testInstrumentationRunner = "com.example.hastanghubaga.HiltTestRunner"
 * }
 * ```
 *
 * ## Summary
 * Without this test runner, Hilt tests will crash with:
 *
 * *"The component was not created. Check that you have added the HiltAndroidRule."*
 *
 * because the default Application does not support Hilt test injection.
 *
 * This runner ensures the correct test Application is used.
 */
class HiltTestRunner : AndroidJUnitRunner() {
    override fun newApplication(
        cl: ClassLoader?,
        className: String?,
        context: Context?
    ): Application {
        return super.newApplication(
            cl,
            "com.example.hastanghubaga.testapp.TestApp_HiltTestApplication",
            context
        )
    }
}

