package com.example.hastanghubaga

import android.app.Application
import android.content.Context
import androidx.test.runner.AndroidJUnitRunner
import dagger.hilt.android.testing.HiltTestApplication
/**
 * app/src/androidTest/java/com/example/hastanghubaga/HiltTestRunner.kt
 *
 * Custom AndroidJUnitRunner for Hilt instrumentation tests.
 *
 * PURPOSE
 * -------
 * Forces Android tests to use the Hilt-generated test Application instead
 * of the production Application.
 *
 * This avoids:
 * - App root conflicts
 * - Multiple Application instantiation errors
 * - Hilt graph contamination
 *
 * CHECKLIST (MUST VERIFY)
 * -----------------------
 * ✓ Extends AndroidJUnitRunner
 * ✓ Overrides newApplication()
 * ✓ Uses TestApp_HiltTestApplication_Application (generated)
 * ✓ Matches instrumentation runner in androidTest manifest
 *
 * COMMON MISTAKES
 * ---------------
 * ✗ Referencing TestApp_HiltTestApplication directly (not generated)
 * ✗ Using production Application class
 * ✗ Forgetting to update the manifest
 *
 * TIPS
 * ----
 * • The `_Application` suffix is REQUIRED (generated by Hilt)
 * • If you see “Cannot process multiple app roots”, check this file
 */

class HiltTestRunner : AndroidJUnitRunner() {
    override fun newApplication(
        cl: ClassLoader?,
        className: String?,
        context: Context?
    ): Application {
        return super.newApplication(
            cl,
            "com.example.hastanghubaga.TestApp_HiltTestApplication_Application",
            context
        )
    }
}


